apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: r2-backend-config
  namespace: default
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: r2-iap-secret
